# -*- coding: utf-8 -*-
"""SDGXI_energy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-ujFzvBlDHj-5DbX93_xAohnOVFLbNI
"""

import pandas as pd
df = pd.read_csv('household_power_consumption.txt', sep=';')

df = df.rename(columns={'Sub_metering_1': 'room1'})
df = df.rename(columns={'Sub_metering_2': 'room2'})
df = df.rename(columns={'Sub_metering_3': 'room3'})

print("First 5 rows of the dataset")
display(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

room_data = df[['room1', 'room2', 'room3']].apply(pd.to_numeric, errors='coerce').sum()

room_data_df = room_data.reset_index()
room_data_df.columns = ['Room', 'Total Energy Consumption']

plt.figure(figsize=(10, 6))
sns.barplot(x='Room', y='Total Energy Consumption', data=room_data_df, palette='viridis')

plt.title('Total Energy Consumption per Room')
plt.xlabel('Room')
plt.ylabel('Total Energy Consumption')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

df['DateTime']=df['Date']+' '+df['Time']
df['DateTime']=pd.to_datetime(df['DateTime'],format='%d/%m/%Y %H:%M:%S')
df=df.set_index('DateTime')
df=df.drop(columns=['Date','Time'])

display(df.head())

numeric_cols = ['Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'room1', 'room2', 'room3']

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print("Data types after converting to numeric:")
print(df[numeric_cols].dtypes)

print("\nMissing values after coercion:")
print(df.isnull().sum())

df.dropna(inplace=True)

print("DataFrame after dropping rows with missing values:")
print(df.isnull().sum())

df_daily=df.resample('D').sum()

print("Shape of the daily aggregated DataFrame:")
print(df_daily.shape)

df_daily['Total_room_consumption']=df_daily['room1']+df_daily['room2']+df_daily['room3']

display(df_daily.head())

target_columns=['room1','room2','room3','Total_room_consumption']

split_index=int(len(df_daily)*0.8)

train_df=df_daily[target_columns].iloc[:split_index]
test_df=df_daily[target_columns].iloc[split_index:]

print(f"Shape of training data: {train_df.shape}")
print(f"Shape of testing data: {test_df.shape}")

from statsmodels.tsa.statespace.sarimax import SARIMAX

sarima_models = {}

for column in target_columns:
    print(f"Training SARIMAX model for {column}...")
    model = SARIMAX(train_df[column], order=(1, 1, 1), seasonal_order=(1, 1, 0, 7), enforce_stationarity=False, enforce_invertibility=False)
    sarima_models[column] = model.fit(disp=False)
    print(f"Model for {column} trained successfully.")

sarima_predictions={}

for column in target_columns:
  start_index=len(train_df)
  end_index=len(df_daily)-1

  forecast=sarima_models[column].predict(start=start_index,end=end_index)
  sarima_predictions[column]=forecast

sarima_predictions_df=pd.DataFrame(sarima_predictions)
sarima_predictions_df.index=test_df.index

display(sarima_predictions_df.head())

for column in target_columns:
  plt.figure(figsize=(12,6))

  plt.plot(test_df.index,test_df[column],label='Actual',color='blue')
  plt.plot(sarima_predictions_df.index,sarima_predictions_df[column],label='Predicted',color='red',linestyle='--')

  plt.title(f'Forecast vs. Actual for {column}')
  plt.xlabel('Date')
  plt.ylabel('Energy Consumption')
  plt.legend()
  plt.grid(True)
  plt.tight_layout()
  plt.show()

def calculate_bill(kwh):
  bill_sen=0

  if kwh<=200:
    bill_sen=kwh*21.80
  elif kwh<=300:
    bill_sen=(200*21.80)+((kwh-200)*33.40)
  elif kwh<=600:
    bill_sen=(200*21.80)+(100*33.40)+((kwh-300)*51.60)
  else:
    bill_sen=(200*21.80)+(100*33.40)+(300*51.60)+((kwh-600)*51.60)
  return bill_sen

sarima_predictions_df['Predicted_Bill_sen']=(sarima_predictions_df['Total_room_consumption']/1000).apply(calculate_bill)

sarima_predictions_df['Predicted_Bill_RM']=sarima_predictions_df['Predicted_Bill_sen']/100

monthly_predictions_df=sarima_predictions_df.resample('M')[['Total_room_consumption']].sum()

monthly_predictions_df['Predicted_Monthly_Bill_sen']=(monthly_predictions_df['Total_room_consumption']/1000).apply(calculate_bill)

monthly_predictions_df['Predicted_Monthly_Bill_RM']=monthly_predictions_df['Predicted_Monthly_Bill_sen']/100

print("Predicted monthly electricity bill:")
display(monthly_predictions_df.head())